#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Gleb Glazov"
email = "glazov.gleb@gmail.com"

[ui]
default-command = "log"
paginate = "never"

[[--scope]]
--when.repositories=["~/private/Dev/work"]
[--scope.user]
email = "gleb.glazov@tripledotstudios.com"
