[settings]
trusted_config_paths = [
  '~/private/Dev',
  '~/.config/mise/config.toml'
]
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
rust      = '1.88.0'
go        = '1.24.5'
nodejs    = '24.4.1'
bun       = '1.2.18'
pnpm      = '10.13.1'
ruby      = '3.4.7'
yarn      = '4.9.2'
python    = '3.13.5'
terraform = '1.12.2'
java      = '24.0.2'
erlang    = '28.0.2'
elixir    = '1.18.4'
uv        = '0.8.15'
lua       = '5.4.8'

[settings.ruby]
ruby_build_opts = "--enable-yjit"
