# xxd -psd

[window]
decorations_theme_variant = "Dark"
dynamic_title = true
option_as_alt = "Both"

[font]
size = 16

# to patch i've used something like that:
#
# docker run --rm \
# -v ~/Downloads/25071581R1LJX4YZ/original:/in \
# -v ~/Downloads/25071581R1LJX4YZ/new:/out \
# nerdfonts/patcher \
# --complete \
# --use-single-width-glyphs \
# --adjust-line-height
#
[font.bold]
family = "BerkeleyMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[font.normal]
family = "BerkeleyMono Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u0015"
key = "Back"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0001"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0005"
key = "Right"
mods = "Command"

# Move between panes
[[keyboard.bindings]]
chars = "\u0002H"
key = "H"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002J"
key = "J"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002K"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002h"
key = "H"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002j"
key = "J"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002k"
key = "K"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002l"
key = "L"
mods = "Command|Shift"

# Resize panes
[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "Right"
mods = "Command|Shift"

# Move between windows
[[keyboard.bindings]]
chars = "\u0002["
key = "LBracket"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002]"
key = "RBracket"
mods = "Command"

# Move windows
[[keyboard.bindings]]
chars = "\u0002{"
key = "{"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002}"
key = "}"
mods = "Command|Shift"

# Projects
[[keyboard.bindings]]
chars = "\u0002p"
key = "P"
mods = "Command"

# Projects
[[keyboard.bindings]]
chars = "\u0002P"
key = "P"
mods = "Command|Shift"

# New session with prompted name
[[keyboard.bindings]]
chars = "\u0002N"
key = "N"
mods = "Command|Shift"

# Rename window
[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

# Rename window
[[keyboard.bindings]]
chars = "\u0002."
key = "Period"
mods = "Command"

# Split panes
[[keyboard.bindings]]
chars = "\u0002d"
key = "D"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002D"
key = "D"
mods = "Command|Shift"

# Quit (?)
[[keyboard.bindings]]
chars = "\u0002d"
key = "Q"
mods = "Command"

# New tab
[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

# Close pane
[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

# Maximize pane
[[keyboard.bindings]]
chars = "\u0002m"
key = "M"
mods = "Command"

# Copy mode
[[keyboard.bindings]]
chars = "\u0002s"
key = "S"
mods = "Command"

# ctrl+digit: send alt+digit
[[keyboard.bindings]]
key = "1"
mods = "Control"
chars = "\u001B1"

[[keyboard.bindings]]
key = "2"
mods = "Control"
chars = "\u001B2"

[[keyboard.bindings]]
key = "3"
mods = "Control"
chars = "\u001B3"

[[keyboard.bindings]]
key = "4"
mods = "Control"
chars = "\u001B4"

[[keyboard.bindings]]
key = "5"
mods = "Control"
chars = "\u001B5"

[[keyboard.bindings]]
key = "6"
mods = "Control"
chars = "\u001B6"

[[keyboard.bindings]]
key = "7"
mods = "Control"
chars = "\u001B7"

[[keyboard.bindings]]
key = "8"
mods = "Control"
chars = "\u001B8"

[[keyboard.bindings]]
key = "9"
mods = "Control"
chars = "\u001B9"

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"

[terminal.shell]
program = "/bin/zsh"
args = ["-l", "-i", "-c", "tmux new-session -A -s main"]
