includes = ["~/private/.config/pop/config.toml"]

projects = [
    { path = "~/.local/share/chezmoi" },
    { path = "~/Dev/*/*" }
]

[[commands]]
key = "ctrl+o"
label = "dev o"
command = "$SHELL -ic 'dev o'"
exit = true

[[worktree.commands]]
key = "ctrl+l"
label = "cleanup"
command = "tmux-branch-cleanup"
exit = true

[[worktree.commands]]
key = "ctrl+a"
label = "new"
command = "tmux-create-worktree"
exit = true
